Resolve circular dependency differently
We have a dependency cycle between `src/sgr/chain/keys.ts` and
`src/sgr/color/color.ts`:

  1. `src/index.ts` imports `src/sgr/index.ts`, which …
  2. imports `src/sgr/sgr.ts`, which …
  3. imports `src/sgr/color/index.ts`, which …
  4. imports `src/sgr/color/color.ts`, which …
  5. imports `src/sgr/color/channel.ts`, which …
  6. imports `src/sgr/context.ts`, which …
  7. imports `src/sgr/format.ts`, which …
  8. imports `src/sgr/chain/index.ts`, which …
  9. imports `src/sgr/chain/keys.ts`, which …
 10. imports `src/sgr/color/index.ts`

There's a cycle between steps 3 and 10.

This kind of cycle often doesn't cause a problem because:

 * In CJS mode, TypeScript compiles code like the following:

   ```ts
   import {foo} from "./foo";

   export function bar() {
       console.log(foo);
   }
   ```

   … into something similar to this:

   ```js
   const foo_1 = require("./foo");

   exports.bar = function bar() {
       console.log(foo_1.foo);
   };
   ```

   Because TypeScript doesn't destructure the module when it's required,
   it's usually okay if it's not done initializing yet (which can be the
   case when it's involved in a circular dependency). It will assign the
   as-yet-uninitialized module object to the `foo_1` variable, but by
   the time `foo_1.foo` is accessed, the module will have finished
   initializing and the property will be available.

 * In ESM mode, module resolution is asynchronous, and the module system
   will wait for the module to finish initializing before it allows
   access to its exports. The net effect is essentially the same as what
   TypeScript does in CJS mode.

But in this case, `keys.ts` tries to access the `channels` export
_during_ the `keys.ts` module's initialization:

```ts
// src/sgr/chain/keys.ts
import {channels}  from "../color";
import {styleKeys} from "../style";

const chainKeys = [...channels, ...styleKeys] as const;
```

Since the `keys.ts` module's initialization depends on a specific export
from the `color` module, that module _has_ to finish initializing before
`keys.ts` can finish initializing. But if `color/index.ts` is loaded
prior to `sgr/chain/index.ts`, then it won't have finished initializing
before `keys.ts` tries to access the `channels` export. In CJS mode,
we'll get a somewhat confusing error message:

```text
TypeError: color_1.channels is not iterable
```

Because the ESM module loader is a little more explicit about dependency
resolution, its error message is slightly more helpful:

```text
ReferenceError: Cannot access 'channels' before initialization
```

But clearly, for both module systems, the cycle causes a problem.

I resolved it by importing `attachChain` directly from `./chain/attach`
in `format.ts`. This avoids the cycle because resolution order becomes
this:

 1. `src/index.ts` imports `src/sgr/index.ts`, which …
 2. imports `src/sgr/sgr.ts`, which …
 3. imports `src/sgr/color/index.ts`, which …
 4. imports `src/sgr/color/color.ts`, which …
 5. imports `src/sgr/color/channel.ts`, which …
 6. imports `src/sgr/context.ts`, which …
 7. imports `src/sgr/format.ts`, which …
 8. imports `src/sgr/chain/attach.ts`.

There are still other cycles in this dependency graph, but none of them
involves access to specific exports during module initialization, so
they don't cause this problem.

But I don't like reaching into module directories like this. I like to
consider the contents of a module directory to be private to that module
and opaque outside of it, using index files to export the public API. So
importing a file from a module directory directly is a code smell to me.

So instead, I've resolve the cycle by making sure that the `chain`
module is loaded first with a new side-effects-only import in
`src/sgr/index.ts`:

```ts
import "./chain";
export * from "./sgr";
```

This turns the dependency graph into this:

 1. `src/index.ts` imports `src/sgr/index.ts`, which …
 2. imports `src/sgr/chain/index.ts`, which …
 3. imports `src/sgr/chain/keys.ts`, which …
 4. imports `src/sgr/color/index.ts`, which …
 5. imports `src/sgr/color/color.ts`, which …
 6. imports `src/sgr/color/channel.ts`, which …
 7. imports `src/sgr/context.ts`, which …
 8. imports `src/sgr/format.ts`, which …
 9. imports `src/sgr/chain/index.ts`.

You can see that a cycle still exists, but it doesn't involve one in
which a module tries to access a specific export before that export is
initialized, because when step 9 is reached, the `chain` module has
already been loaded and initialization isn't attempted on it at this
time. That allows the loader to climb back up the dependency graph and
finish initializing the previous modules, allowing `color.ts` to finish
initializing before `keys.ts` tries to access its `channels` export.

This is still a hack, and could even be considered a more fragile one.
Nonetheless, it smells slightly less bad to me. I've included a comment
briefly explaining this side-effects-only import, so hopefully it won't
result in confusion for future maintainers.

Obviously, there are no functional changes in this commit.